### ISSUE TITLE
Important readme update for running Homura

### ISSUE THREAD

**Issue by rwbc** [RedBedHed/Homura-Thesis-Version#1]
Hi Ellie,

I had recently added Homura to my WB/UCI chronology and compiled two WIN binaries (sse4.1/nopop + bmi2)
with GCC in Msys2, which I made available to the public. To my surprise I got some user feedback that both did not run at all
at the users' machine with some weird error.
```
SYNTAX ERROR in token 1.
Reached EOF.
```

After some retesting on my local machine I finally found the reason ;)
Obviously my first succeeding test was with a fresh compiled binary in the src directory,
but the download just contained my binaries and two readmes plus link to the source,
while Homura **needs** this **ospec.txt** file in the running directory!
Please mention this necessity in the github readme.

Thanks for your program!

Guenther
https://docs.google.com/spreadsheets/d/1GXoy3lGhdKPJbatdw2_2dhWT3TkpthPcNtHs51MQydM

**Comment by RedBedHed** [comment]
Hi Guenther,

I will fix this asap! Thank you for bringing it to my attention!

I initially designed the lexical analyzer for a toy language that I plan to build someday, and it does need that ospec.txt file as input. I completely forgot about it.

Thank you!

Ellie
